#!/usr/bin/env python3
import sys
from abct.abct import pn, dn
from abct.output import abct_out, bct, has_out

p, d, *_ = (int(a) for a in sys.argv[1:3] + [2])

while d: print(abct_out(d).decode()[abct_out(d).decode().rfind(chr(2))+1:], end='', flush=True) if has_out(p, d) else 0; p, d = (pn(p), dn(p, d))
